name: 'Build'

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * *"
    
jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Powershell script runner
      run: .\prepare.ps1
